# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: test

on:
  push:
    branches: [ "main","add_test_cases" ]
  pull_request:
    branches: [ "main","add_test_cases" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18.x'
          cache-dependency-path: go.sum
      - name: Install dependencies
        run: go get .
      - name: Start Mosquitto
        uses: namoshek/mosquitto-github-action@v1
        with:
          version: '1.6'
          ports: '1883:1883'
      - name: Build plugin
        run: go build -buildmode=plugin -o plugin.so testdata/plugin/plugin.go
      - name: Run unit tests and integrated tests
        run: go test -v --tags=test_plugin ./... -coverprofile="codecov.report"
        env:
          TEST_SERVER_IP: ${{ secrets.TEST_SERVER_IP }}
          TEST_SERVER_USERNAME: ${{ secrets.TEST_SERVER_USERNAME }}
          TEST_SERVER_PASSWORD: ${{ secrets.TEST_SERVER_PASSWORD }}
          TEST_SMTP_USERNAME: ${{ secrets.TEST_SMTP_USERNAME }}
          TEST_SMTP_PASSWORD: ${{ secrets.TEST_SMTP_PASSWORD }}
          TEST_SSE_SERVER: ${{ secrets.TEST_SSE_SERVER }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}